AWSTemplateFormatVersion: "2010-09-09"
Description: |
  An S3 Bucket that holds Cassandra configuration and files needed for secure node-to-node and client-to-node encryption

Parameters:
  S3BucketName:
    Type: String
    Default: "cassandra-configuration"

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName

Outputs:
  BucketName:
    Description: The S3 bucket that holds Cassandra configuration and certificates
    Value: !Ref 'S3Bucket'
    Export:
      Name: !Sub '${AWS::StackName}-CassandraBucket'
